// Handles a user can never claim — prevents impersonating the app itself,
// a system/support role, or a URL segment the app already uses (or might
// use later, e.g. a future /[handle] public profile route colliding with
// /dashboard). Exact-match only; all entries are lowercase to match
// HANDLE_PATTERN's output.
const RESERVED_HANDLES = new Set([
  // App/brand identity
  "jeet-yet",
  "jeetyet",
  "jeet",
  "jeetyetapp",
  "jeet-yet-app",

  // Existing and likely-future app routes
  "dashboard",
  "profile",
  "profiles",
  "onboarding",
  "recipe",
  "recipes",
  "auth",
  "api",
  "sign-in",
  "signin",
  "sign-up",
  "signup",
  "sign-out",
  "signout",
  "login",
  "logout",
  "log-in",
  "log-out",
  "register",
  "session",
  "share",
  "settings",
  "account",
  "accounts",
  "handle",
  "handles",

  // System/administrative roles
  "admin",
  "administrator",
  "administrators",
  "root",
  "superadmin",
  "super-admin",
  "superuser",
  "super-user",
  "moderator",
  "moderators",
  "mod",
  "mods",
  "staff",
  "owner",
  "owners",
  "official",
  "system",
  "sysadmin",

  // Support/contact/business functions
  "support",
  "help",
  "helpdesk",
  "help-desk",
  "contact",
  "contact-us",
  "info",
  "feedback",
  "abuse",
  "report",
  "security",
  "legal",
  "privacy",
  "terms",
  "billing",
  "payments",
  "sales",
  "press",
  "media",
  "marketing",
  "webmaster",
  "postmaster",
  "hostmaster",

  // Generic web/infra conventions
  "www",
  "web",
  "mail",
  "email",
  "ftp",
  "smtp",
  "dns",
  "cdn",
  "static",
  "assets",
  "images",
  "img",
  "download",
  "downloads",
  "upload",
  "uploads",
  "docs",
  "documentation",
  "status",
  "health",
  "healthcheck",
  "ping",

  // Bots/services/automation
  "bot",
  "bots",
  "service",
  "services",
  "noreply",
  "no-reply",
  "donotreply",
  "do-not-reply",
  "notification",
  "notifications",
  "alert",
  "alerts",
  "cron",
  "worker",
  "workers",
  "daemon",

  // Placeholder/null-like values
  "null",
  "undefined",
  "none",
  "nil",
  "na",
  "n-a",
  "unknown",
  "anonymous",
  "anon",
  "guest",
  "guests",
  "test",
  "testing",
  "demo",
  "example",
  "sample",
  "placeholder",
  "temp",
  "temporary",
  "default",
  "deleted",
  "banned",
  "suspended",
  "blocked",
  "inactive",
  "disabled",

  // Self-referential/generic pronouns
  "me",
  "you",
  "everyone",
  "everybody",
  "all",
  "nobody",
  "someone",
  "somebody",

  // Common reserved UI/action words
  "new",
  "edit",
  "delete",
  "remove",
  "create",
  "update",
  "list",
  "search",
  "browse",
  "explore",
  "discover",
  "trending",
  "popular",
  "top",
  "featured",
  "home",
  "index",
  "main",
  "app",
  "apps",
  "mobile",
  "ios",
  "android",
  "web-app",

  // Government/legal (impersonation-prone)
  "government",
  "gov",
  "police",
  "fbi",
  "irs",
]);

export { RESERVED_HANDLES };
