import type { Metadata } from "next";
import { firaCode, raleway } from "@/fonts";
import "./globals.css";
import { cn } from "@/lib/utils";
import Header from "@/components/layout/header";
import Providers from "@/providers/providers";
import Footer from "@/components/layout/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={cn(
        "h-full",
        "antialiased",
        raleway.variable,
        firaCode.variable,
      )}
    >
      <body className="flex min-h-full flex-col">
        <Providers>
          <Header />
          <main className="mt-12 flex flex-1 flex-col">{children}</main>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
